### ISSUE TITLE
Swarm size community design sketch

### ISSUE THREAD

**Issue by MaChengxin** [MaChengxin/tribler#1]
## Goal
Create a community which every second starts a new content popularity check.
The outcome of this check is shared across the Dispersy overlay with 10 neighbors (fanout).
Each peer in the network now obtains UDP packets with popularity starts on several swarms.

## TODO

- [x] Make sure the basic understanding of Dispersy is correct (by asking others)
- [x] Build a new community (starting point: sending some dummy data)
- [x] Use multiple machines to run the community
- [x] Integrate the swarm size detector into SwarmSizeCommunity

**Comment by MaChengxin** [comment]
The issue was originally put [here](https://github.com/MaChengxin/expBT/issues/11).

**Comment by MaChengxin** [comment]
## Use multiple machine to run the community
### Configuration
number of nodes: 20
number of neighbors per node: 10

### What to expect
each node can receive message from all of its neighbors

### Question
How to generate the graph (i.e. how to assign neighbors to nodes?)

**Comment by MaChengxin** [comment]
## Integrate the swarm size detector in SwarmSizeCommunity
### Goal
Replace the dummy data in the SwarmSizeCommunity by actual data
